In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("recipes_extended.csv")

In [7]:
df.head()

,recipe_title,category,subcategory,description,ingredients,directions,num_ingredients,num_steps,ingredient_text,directions_text,...,is_halal,is_kosher,is_nut_free,is_dairy_free,is_gluten_free,dietary_profile,healthiness_score,health_flags,main_ingredient,health_level
0,Air Fryer Potato Slices with Dipping Sauce,Air Fryer Recipes,Air Fryer Recipes,"These air fryer potato slices, served with a b...","[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...","[""Combine ketchup, beer, Worcestershire sauce,...",9,5,ketchup beer worcestershire sauce onion powder...,"combine ketchup, beer, worcestershire sauce, o...",...,False,True,True,True,True,"[""vegan"", ""gluten_free"", ""nut_free"", ""kosher""]",80,"[""plant_based"", ""healthy_fats"", ""fried""]",unknown,healthy
1,Gochujang Pork Belly Bites,Air Fryer Recipes,Air Fryer Recipes,These gochujang pork belly bites are sweet and...,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...","[""Preheat an air fryer to 400 degrees F (200 d...",5,4,pound pork belly gochujang soy sauce honey gro...,preheat an air fryer to 400 degrees f (200 deg...,...,False,False,True,True,True,"[""gluten_free"", ""nut_free""]",64,"[""sugary""]",red_meat,moderate
2,3-Ingredient Air Fryer Everything Bagel Chicke...,Air Fryer Recipes,Air Fryer Recipes,These 3-ingredient air fryer everything bagel ...,"[""1 ¼ pounds chicken tenders"", ""1 tablespoon o...","[""Gather all ingredients. Preheat an air fryer...",3,4,¼ pounds chicken tenders olive oil everything ...,gather all ingredients. preheat an air fryer t...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",68,"[""healthy_fats"", ""fried""]",poultry,moderate
3,Air Fryer Everything Bagel Chicken Cutlets,Air Fryer Recipes,Air Fryer Recipes,These air fryer everything bagel chicken cutle...,"[""4 chicken cutlets (about 1 pound total)"", ""s...","[""Preheat an air fryer to 400 degrees F (200 d...",9,9,chicken cutlets about pound total salt freshly...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,False,False,"[""nut_free"", ""halal"", ""kosher""]",70,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",poultry,moderate
4,Air Fryer Honey Sriracha Salmon Bites,Air Fryer Recipes,Air Fryer Recipes,These air fryer honey Sriracha salmon bites ar...,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...","[""Preheat an air fryer to 400 degrees F (200 d...",5,5,soy sauce honey sriracha rice vinegar granulat...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",74,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",unknown,moderate

In [8]:
import pandas as pd

In [9]:
df.head(5) #-> Primeras 5 filas de su archivo
df.head(5) #-> Primeras n filas de archivo

,recipe_title,category,subcategory,description,ingredients,directions,num_ingredients,num_steps,ingredient_text,directions_text,...,is_halal,is_kosher,is_nut_free,is_dairy_free,is_gluten_free,dietary_profile,healthiness_score,health_flags,main_ingredient,health_level
0,Air Fryer Potato Slices with Dipping Sauce,Air Fryer Recipes,Air Fryer Recipes,"These air fryer potato slices, served with a b...","[""3/4 cup ketchup"", ""1/2 cup beer"", ""1 tablesp...","[""Combine ketchup, beer, Worcestershire sauce,...",9,5,ketchup beer worcestershire sauce onion powder...,"combine ketchup, beer, worcestershire sauce, o...",...,False,True,True,True,True,"[""vegan"", ""gluten_free"", ""nut_free"", ""kosher""]",80,"[""plant_based"", ""healthy_fats"", ""fried""]",unknown,healthy
1,Gochujang Pork Belly Bites,Air Fryer Recipes,Air Fryer Recipes,These gochujang pork belly bites are sweet and...,"[""1 pound pork belly"", ""1/4 cup gochujang"", ""2...","[""Preheat an air fryer to 400 degrees F (200 d...",5,4,pound pork belly gochujang soy sauce honey gro...,preheat an air fryer to 400 degrees f (200 deg...,...,False,False,True,True,True,"[""gluten_free"", ""nut_free""]",64,"[""sugary""]",red_meat,moderate
2,3-Ingredient Air Fryer Everything Bagel Chicke...,Air Fryer Recipes,Air Fryer Recipes,These 3-ingredient air fryer everything bagel ...,"[""1 ¼ pounds chicken tenders"", ""1 tablespoon o...","[""Gather all ingredients. Preheat an air fryer...",3,4,¼ pounds chicken tenders olive oil everything ...,gather all ingredients. preheat an air fryer t...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",68,"[""healthy_fats"", ""fried""]",poultry,moderate
3,Air Fryer Everything Bagel Chicken Cutlets,Air Fryer Recipes,Air Fryer Recipes,These air fryer everything bagel chicken cutle...,"[""4 chicken cutlets (about 1 pound total)"", ""s...","[""Preheat an air fryer to 400 degrees F (200 d...",9,9,chicken cutlets about pound total salt freshly...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,False,False,"[""nut_free"", ""halal"", ""kosher""]",70,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",poultry,moderate
4,Air Fryer Honey Sriracha Salmon Bites,Air Fryer Recipes,Air Fryer Recipes,These air fryer honey Sriracha salmon bites ar...,"[""1 tablespoon soy sauce"", ""1 tablespoon honey...","[""Preheat an air fryer to 400 degrees F (200 d...",5,5,soy sauce honey sriracha rice vinegar granulat...,preheat an air fryer to 400 degrees f (200 deg...,...,True,True,True,True,True,"[""gluten_free"", ""nut_free"", ""halal"", ""kosher""]",74,"[""plant_based"", ""healthy_fats"", ""sugary"", ""fri...",unknown,moderate